services:
  backend:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/dbname
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "dbname"]
      interval: 10s
      retries: 5
      start_period: 10s
